apiVersion: v1
kind: Service
metadata:
  name: nginx-svc
  namespace: monitoring
  labels:
    app: nginx-svc
spec:
  clusterIP: 10.68.80.80
  ports:
  - port: 80
    targetPort: 80
    name: http
  - port: 443
    targetPort: 443
    name: https
  selector:
    app: nginx

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: nginxconfig
  namespace: monitoring
data:
  nginx.conf: |
    user  root root;
    worker_processes  4;
    worker_rlimit_nofile 104800;
    error_log  /data/logs/nginx/error.log warn;

    pid        /var/run/nginx.pid;

    events {
        use epoll;
        worker_connections 104800;
        accept_mutex off;
    }

    http {
        include       mime.types;
        default_type  application/octet-stream;

        log_format  main  '$remote_addr $http_x_forwarded_for - [$time_local] "$request" '
                          '$request_time $upstream_response_time "$upstream_addr" '
                          '$status $body_bytes_sent "$http_referer" '
                          '"$http_user_agent" $upstream_cache_status';

        access_log  /data/logs/nginx/access.log  main;
        map $http_upgrade $connection_upgrade {
        default upgrade;
        ''      close;
        }

        charset utf-8;
        server_names_hash_bucket_size 128;
        client_header_buffer_size 16k;
        large_client_header_buffers 4 8k;
        client_max_body_size 512m;
        sendfile on;
        sendfile_max_chunk 2048k;
        tcp_nopush on;
        tcp_nodelay on;
        client_header_timeout 300s;
        client_body_timeout 300s;
        send_timeout 300s;
        keepalive_timeout  480;
        keepalive_requests 10000;
        server_tokens off;
        client_body_temp_path /tmp 1 2;
        client_body_buffer_size 16m;
        client_body_in_file_only off;
        chunked_transfer_encoding off;

        gzip on;
        gzip_disable "msie6";
        gzip_proxied any;
        gzip_min_length 1k;
        gzip_buffers 4 16k;
        gzip_http_version 1.1;
        gzip_comp_level 4;
        gzip_types text/plain text/htm text/css application/x-javascript text/xml application/xml application/xml+rss text/javascript application/javascript application/json;
        gzip_vary on;

        proxy_connect_timeout 600s;
        proxy_read_timeout 600s;
        proxy_send_timeout 600s;
        #proxy_next_upstream http_502 http_504 http_404 error timeout invalid_header;
        proxy_redirect off;
        proxy_set_header Host $http_host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header RealURL $scheme://$host$request_uri;
        proxy_buffering on;
        proxy_buffer_size 64k;
        proxy_buffers 16 4m;
        proxy_busy_buffers_size 32m;
        proxy_temp_file_write_size 64m;

        fastcgi_connect_timeout 300;
        fastcgi_send_timeout 300;
        fastcgi_read_timeout 300;
        fastcgi_buffer_size 16k;
        fastcgi_buffers 16 16k;
        fastcgi_busy_buffers_size 32k;
        fastcgi_temp_file_write_size 64k;

        server
        {
            listen 80 default_server;
            server_name - "";
            access_log /data/logs/nginx/default.log main;

            location / {
                #The location setting lets you configure how nginx responds to requests for resources within the server.
                root   html;
                index  index.html index.htm;
            }

            error_page   500 502 503 504  /50x.html;
            location = /50x.html {
                root   html;
            }

        }


        include /usr/local/nginx/conf.d/*.conf;
    }
---

apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: nginx
  namespace: monitoring
spec:
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: "isnginx"
                operator: In
                values:
                - "nginx"
      tolerations:
      - operator: "Exists"
      #nodeSelector:
      #  kubernetes.io/hostname: prod-zk01
      #dnsPolicy: ClusterFirstWithHostNet # 如果使用主机网络，则启用 
      #hostNetwork: true                  # 如果使用主机网络，则启用
      hostAliases:
      - ip: 127.0.0.1
        hostnames:
        - "test.abc.com"
      volumes:
      - name: logs
        hostPath:
          path: /data/logs/nginx
          type: DirectoryOrCreate
      - name: nginxconf
        hostPath:
          path: /data/nginx
          type: Directory
      - name: nginxconfig
        configMap:
          name: nginxconfig
      containers:
      - name: nginx
        image: nginx:1.21.1-perl
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 80
          name: http
          hostPort: 80
        - containerPort: 443
          name: https
          hostPort: 443
        livenessProbe:
          initialDelaySeconds: 20
          failureThreshold: 3
          periodSeconds: 60
          successThreshold: 1
          tcpSocket:
            port: 80
          timeoutSeconds: 1
        resources:
          requests:
            cpu: "500m"
            memory: 4Gi
          limits:
            cpu: "2000m"
            memory: 8Gi
        volumeMounts:
        - name: nginxconfig
          mountPath: /etc/nginx/nginx.conf
          subPath: nginx.conf
        - name: logs
          mountPath: /data/logs/nginx
        - name: nginxconf
          mountPath: /usr/local/nginx
